//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModels
    {
        public int CarModelID { get; set; }
        public int ManufactorID { get; set; }
        public string Name { get; set; }
        public bool IsShown { get; set; }
    
        public virtual Manufactors Manufactors { get; set; }
    }
}
