//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossEntities
{
    using System;
    
    public partial class CrossSelection
    {
        public string Code { get; set; }
        public string TypeTsName { get; set; }
        public string ManufactorName { get; set; }
        public string ModelName { get; set; }
        public string MotorName { get; set; }
        public string EngineName { get; set; }
        public string Comment { get; set; }
    }
}
