//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GoodWillDbContext : DbContext
    {
        public GoodWillDbContext()
            : base("name=GoodWillDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModels> CarModels { get; set; }
        public virtual DbSet<Manufactors> Manufactors { get; set; }
        public virtual DbSet<Motors> Motors { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsAndMotors> ProductsAndMotors { get; set; }
        public virtual DbSet<ProductsAndOes> ProductsAndOes { get; set; }
        public virtual DbSet<VenycleTypes> VenycleTypes { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<CrossSelection> pr_GetCrossSelection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CrossSelection>("pr_GetCrossSelection");
        }
    }
}
