//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossEntities
{
    using System;
    
    public partial class CrossSelectionResult
    {
        public string Code { get; set; }
        public string TypeTs { get; set; }
        public string ManufactorTS { get; set; }
        public string Model { get; set; }
        public string MotorName { get; set; }
        public string MotorEngine { get; set; }
        public string Comment { get; set; }
    }
}
