//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motors()
        {
            this.ProductsAndMotors = new HashSet<ProductsAndMotors>();
        }
    
        public int MotorID { get; set; }
        public int CarModelID { get; set; }
        public string Name { get; set; }
        public string Engine { get; set; }
        public string CardanShaft { get; set; }
        public string HoursePower { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsShown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsAndMotors> ProductsAndMotors { get; set; }
    }
}
