//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public int PartnerID { get; set; }
        public int RoleID { get; set; }
        public string Login { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> FireDate { get; set; }
        public bool IsActive { get; set; }
        public System.Guid Password { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
    }
}
